site_name: SWD Project Documentation
site_url: https://projectswd12.github.io/SWD_Project/
use_directory_urls: true

theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: README.md
  - Project Overview:
      - Changelog: CHANGELOG.md
      - License: LICENSE.md
      - About the Project: README.md
  - Documentation:
      - Secrets Management: secrets-management.md
      - Architecture:
          - Overview: architecture/architecture.md
      - Automation:
          - Continuous Integration: automation/continuous-integration.md
          - Continuous Delivery: automation/continuous-delivery.md
      - Quality Attributes:
          - Attribute Scenarios: quality-attributes/quality-attribute-scenarios.md
      - Quality Assurance:
          - User Acceptance Tests: quality-assurance/user-acceptance-tests.md
          - Automated Tests: quality-assurance/automated-tests.md
